name: docker-workflow

on:
  push:
    branches: 
      - master


jobs:
  build_and_upload_image:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to hub
      uses: docker/login-action@v1
      with:
        username: sameertahir23
        password: sameer1@3

    - name: build image and upload
      run: |
        docker build -t python-app2:latest .
        docker push python-app2:latest

    # - name: run container
    #   run: docker run -d -p 5000:8000 python-app2:latest
